services:
  broker:
    build: .
    container_name: broker
    command: python -m broker.broker
    ports:
      - "6001:6001/udp"
      - "5002:5002"
    networks:
      - iot_net

  sensor_temp:
    build: .
    container_name: sensor_temp
    command: python -m sensors.sensor_temp
    depends_on:
      - broker
    networks:
      - iot_net

  sensor_fumaca:
    build: .
    container_name: sensor_fumaca
    command: python -m sensors.sensor_fumaca
    depends_on:
      - broker
    networks:
      - iot_net

  atuador_aquecedor:
    build: .
    container_name: atuador_aquecedor
    command: python -m actuators.atuador_aquecedor
    depends_on:
      - broker
    networks:
      - iot_net

  atuador_exaustor:
    build: .
    container_name: atuador_exaustor
    command: python -m actuators.atuador_exaustor
    depends_on:
      - broker
    networks:
      - iot_net

  client:
    build: .
    container_name: client
    command: python -m client.client
    depends_on:
      - broker
    stdin_open: true
    tty: true
    networks:
      - iot_net

networks:
  iot_net:
    driver: bridge
